name: Deploy to Netlify

on:
  push:
    branches:
      - master  # أو main حسب اسم الفرع بتاعك

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # أو الإصدار اللي بتشتغل عليه

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm run build
          ls -R dist  # اعرض محتويات مجلد البناء
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist  # خلي بالك من --prod عشان يروح على الدومين الرئيسي
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}